### ISSUE TITLE
Integrate another project

### ISSUE THREAD

**Issue by thewh1teagle** [spacedriveapp/native-deps#5]
Hello!
I created cross platform desktop app [vibe](https://github.com/thewh1teagle/vibe)
And I used there the crate [rust-ffmpeg](https://github.com/zmwangx/rust-ffmpeg#readme).

I need to ship it in a way that users won't need to install anything related to ffmpeg and just use it immediatly.
So I need either static link ffmpeg or add it somehow to `tauri` deps.
I saw that you did a lot of work about it so I wondering if I can use this repo somehow as solution for mine,
or alternativly if you have idea how can I do that locally + in CI in simple way, for instance tried to link with `brew` package of `ffmpeg` and it didn't worked.

**Comment by thewh1teagle** [comment]
Yes I figured out after many different things I tried 😅
But I'm satisfied with the solution which works good both in ci and locally.
ffmpeg have many dependencies and it was hard because I wanted to statically link it.

Thanks!
Both Spacerive and this repo is great inspiration!

**Comment by HeavenVolkoff** [comment]
I am glad you found a working solution. Feel free to open a new issue if you need help with anything else in the future.
